### PR TITLE
Implement syntactic support for GNU's imaginary constants

### PR DESCRIPTION
**Pull request by ludanpr**
Implement support for imaginary constants, mentioned at PR #86 . I'm opening it as a draft for you to take a look.
In particular, the changes to `Lexer::lexIntegerOrFloatingConstant` and the (possible) additional `Lexer::DiagnosticsReporter::`

### CODE REVIEW

**Comment by ltcmelo** [comment]
Looks on the right track to me @ludanpr .

**Review by ltcmelo — COMMENTED** [review]
Hi @ludanpr , I like most of the PR but there are 2 points that I'm uncertain about… 

1. The method `lexImaginaryConstant` contains too many branches and redundancies within it. It also has an "look backward" to check whether the raw token is integer/floating; such a look backward should/can be avoided. I'm afraid these facts can affect the performance of the lexer a lot for the ordinary situation (where imaginary constants won't exist).

2. With the current `ImaginaryConstant` lexeme, the information of whether the constant is an integer or a floating is lost. The absence of these information will lead a higher cost for the  subsequence semantic phases (e.g., in type checking). What would be good here is either (i) enriching the `IntegerConstant` and `FloatingConstant` with an imaginary component or (ii) two `ImaginaryIntegerConstant` and `ImaginaryFloatingConstant` lexemes. From the top of my mind, I prefer option (ii).

A more detailed comment about the implementation of item 1: it seems to me that mixing the decision of integer/floating X imaginary in the same method wouldn't lead to good performance (unless you use a `goto` — there are examples in other parts of the lexer); alternatively, you come with an more methods such as `lexFloatingSuffixAndMaybeImaginary`/`lexIntegerSuffixAndMaybeImaginary` and `lexImaginarySuffixIntegerOrFloating`, even if there's some (small) code redundancy there, as long as clarity is kept.

**Comment by ludanpr** [comment]
Got it @ltcmelo , thanks for the feedback. I'm gonna work on them.

**Comment by ludanpr** [comment]
While working on this PR, I stumbled across on what appears to be a small bug. With the (additional) test case:

```c++
void ParserTest::case1093()
{
    parseExpression(".1f",
                    Expectation().AST( { FloatingConstantExpression }));
}
```

it fails:

```
	-------------------------------------------------
	PARSER-case1093... mismatch in ERROR count
!	FAIL
		Expected: 0
		Actual  : 1
		/home/luan/Documentos/psychec/C/tests/Test.cpp:97

	-------------------------------------------------
```

on

```
Author: Leandro T. C. Melo <ltcmelo@gmail.com>
Date:   Fri May 20 20:24:52 2022 -0300

    (initial) type binding and tests (#102)
```

which was tracked to:

https://github.com/ltcmelo/psychec/blob/b3cf4245dc78d0940e4f2a77f5d1fcd755d1b404/C/parser/Lexer.cpp#L916-L922

**Comment by ltcmelo** [comment]
@ludanpr thanks for the but discovery/report! 

I just pushed a fix to it. 

It could be that my fix requires you to do some adjustments in your PR, sorry for that. But it could also be that my fix gives you additional insight on [my previous comments about avoiding the lexer to "look backwards"](https://github.com/ltcmelo/psychec/pull/99#pullrequestreview-979395311).

**Comment by ludanpr** [comment]
I was indeed taking the approach you suggested. Thank you :+1:

**Comment by ltcmelo** [comment]
Thanks @ludanpr for the good work 🙂 

I just merged the PR (I will just make a minor adjustment a method of lexer later).

**Pull request merged**
